let mockTData = {
    peoples: "https://source.unsplash.com/random",
    status: null, // Accepts string, 100, 1- 5
    text: null,
    date: null,
    numbers: null,
    timeline: null,
    tags: null,
    rating: null,
    worldClock: null,
    checkbox: null,
    link: null,
    log: null,
    autoInt: null,
    countryCol: null,
    vote: null,
    teamCol: null,
    locationCol: null,
    weekCol: null,
    progressTrack: null,
    longTextCol: null,
    phoneCol: null,
    itemIdCol: null,
    formulaCol: null,
    colorPicker: null,
    lastUpdated: null,
    timeTrackingCol: null,
    fileCol: null
}